plugins:
   - jest


env:
  node: true
  jest: true

  #parser: babel-eslint

extends:
  - "airbnb-base"
  - "prettier"
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0
  no-unused-vars: 0
  